# Generated by Django 4.2.15 on 2024-08-22 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transit_bbs', '0004_post_interested_users_delete_postinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='interested_users',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='PostView',
        ),
        migrations.AddField(
            model_name='postinterest',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit_bbs.post'),
        ),
        migrations.AddField(
            model_name='postinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
