# Generated by Django 4.2.15 on 2024-08-23 04:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transit_bbs', '0006_postview'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='interested_users',
            field=models.ManyToManyField(blank=True, related_name='interested_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PostInterest',
        ),
    ]
