# Generated by Django 5.1 on 2024-09-04 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_post_author_remove_post_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='attachment',
            new_name='attached_file',
        ),
    ]
