# Generated by Django 5.1 on 2024-09-06 01:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_attachment_post_attached_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='viewed_by',
        ),
        migrations.AddField(
            model_name='post',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
