# Generated by Django 5.1 on 2024-09-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='new_comment',
            field=models.BooleanField(default=False),
        ),
    ]
