# Generated by Django 5.1 on 2024-09-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_post_new_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='new_comment',
            new_name='new_comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='new_comment',
            field=models.BooleanField(default=True),
        ),
    ]
