# Generated by Django 5.1 on 2024-09-11 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_new_comment_post_new_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='new_comments',
            new_name='new_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='new_comment',
        ),
    ]
