# Generated by Django 5.1.1 on 2024-09-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_bentoreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BentoUnavailableDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='bentoreservation',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
