# Generated by Django 5.1.1 on 2024-09-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_bentounavailableday_bentoreservation_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bentoreservation',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
