# Generated by Django 5.1.1 on 2024-09-24 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_bentoreservation_memo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bentoreservation',
            name='transfer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_reservations', to=settings.AUTH_USER_MODEL, verbose_name='振替ユーザー'),
        ),
        migrations.AlterField(
            model_name='bentoreservation',
            name='rice_gram',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bentoreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
