# Generated by Django 5.1.1 on 2024-09-24 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_bentoreservation_transfer_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bentoreservation',
            name='transfer_to',
        ),
        migrations.AlterField(
            model_name='bentoreservation',
            name='rice_gram',
            field=models.IntegerField(blank=True, choices=[(100, '100g'), (160, '160g'), (200, '200g')], null=True),
        ),
        migrations.AlterField(
            model_name='bentoreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
