# Generated by Django 5.1 on 2024-11-19 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_userchangelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bentoreservation',
            options={'verbose_name': '弁当予約', 'verbose_name_plural': '弁当予約一覧'},
        ),
        migrations.AlterModelOptions(
            name='bentounavailableday',
            options={'verbose_name': '予約不可日', 'verbose_name_plural': '予約不可日一覧'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '投稿', 'verbose_name_plural': '投稿一覧'},
        ),
        migrations.CreateModel(
            name='KakeiboEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('income', '収入'), ('expense', '支出')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='kakeibo_images/')),
                ('is_planned', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kakeibo_entries', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='accounts.tag')),
            ],
        ),
    ]
