# Generated by Django 5.1 on 2024-11-19 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_tag_color_alter_tag_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='kakeiboentry',
            old_name='description',
            new_name='memo',
        ),
        migrations.RemoveField(
            model_name='kakeiboentry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='kakeiboentry',
            name='image',
        ),
        migrations.RemoveField(
            model_name='kakeiboentry',
            name='is_planned',
        ),
        migrations.RemoveField(
            model_name='kakeiboentry',
            name='tags',
        ),
        migrations.AddField(
            model_name='kakeiboentry',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kakeiboentry',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tag'),
        ),
        migrations.AlterField(
            model_name='kakeiboentry',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kakeiboentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
