# Generated by Django 5.1 on 2024-11-21 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_rename_description_kakeiboentry_memo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakeiboentry',
            name='category',
            field=models.CharField(choices=[('income', '収入'), ('expense', '支出')], max_length=20),
        ),
        migrations.AlterField(
            model_name='kakeiboentry',
            name='scheduled_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
