# Generated by Django 5.1 on 2024-11-22 02:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_kakeiboentry_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kakeiboentry',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='kakeiboentry',
            name='scheduled_date',
        ),
        migrations.AddField(
            model_name='kakeiboentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='kakeiboentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kakeibo_images/'),
        ),
        migrations.AddField(
            model_name='kakeiboentry',
            name='status',
            field=models.CharField(choices=[('confirmed', '確定済み'), ('pending', '未確定')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='kakeiboentry',
            name='transaction_type',
            field=models.CharField(choices=[('income', '収入'), ('expense', '支出')], default='expense', max_length=10),
        ),
        migrations.AddField(
            model_name='kakeiboentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kakeiboentry',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
