# Generated by Django 5.1 on 2024-11-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_kakeiboentry_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakeiboentry',
            name='status',
            field=models.CharField(choices=[('確定済み', '確定済み'), ('未確定', '未確定')], default='未確定', max_length=10),
        ),
        migrations.AlterField(
            model_name='kakeiboentry',
            name='transaction_type',
            field=models.CharField(choices=[('収入', '収入'), ('支出', '支出')], default='支出', max_length=10),
        ),
    ]
