# Generated by Django 5.1 on 2024-11-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_kakeiboentry_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakeiboentry',
            name='status',
            field=models.CharField(choices=[('confirmed', '確定済み'), ('pending', '未確定')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='kakeiboentry',
            name='transaction_type',
            field=models.CharField(choices=[('income', '収入'), ('expense', '支出')], default='expense', max_length=10),
        ),
    ]
