# Generated by Django 5.1 on 2024-11-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_kakeiboentry_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakeiboentry',
            name='created_at',
            field=models.DateField(),
        ),
    ]
