# Generated by Django 5.1 on 2025-01-08 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_bentoreservation_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bentoreservation',
            name='created_at',
        ),
    ]
