# Generated by Django 5.1 on 2025-01-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_bentoreservation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bentoreservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
