# Generated by Django 5.1 on 2025-01-16 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_bentoreservation_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_3', models.CharField(max_length=255, verbose_name='第3位の映画')),
                ('reason_3', models.TextField(verbose_name='第3位の理由')),
                ('rank_2', models.CharField(max_length=255, verbose_name='第2位の映画')),
                ('reason_2', models.TextField(verbose_name='第2位の理由')),
                ('rank_1', models.CharField(max_length=255, verbose_name='第1位の映画')),
                ('reason_1', models.TextField(verbose_name='第1位の理由')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
