# Generated by Django 5.1 on 2025-01-28 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0035_favoritemoviescomment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bentoreservation",
            name="original_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="original_reservations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="振替元",
            ),
        ),
        migrations.AlterField(
            model_name="bentoreservation",
            name="reservation_date",
            field=models.DateField(verbose_name="予約日"),
        ),
        migrations.AlterField(
            model_name="bentoreservation",
            name="rice",
            field=models.BooleanField(default=False, verbose_name="ごはん"),
        ),
        migrations.AlterField(
            model_name="bentoreservation",
            name="rice_gram",
            field=models.IntegerField(blank=True, null=True, verbose_name="グラム数"),
        ),
        migrations.AlterField(
            model_name="bentoreservation",
            name="side_dish",
            field=models.BooleanField(default=False, verbose_name="おかず"),
        ),
        migrations.AlterField(
            model_name="bentoreservation",
            name="transfer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transferred_reservations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="振替先",
            ),
        ),
        migrations.AlterField(
            model_name="bentoreservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="予約者",
            ),
        ),
    ]
