# Generated by Django 5.1 on 2025-02-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_bbspost_bbscomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbspost',
            name='likes',
        ),
    ]
