# Generated by Django 5.1 on 2025-02-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_remove_bbspost_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bbscomment',
            old_name='parent',
            new_name='parent_comment',
        ),
    ]
