# Generated by Django 5.1 on 2025-05-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0039_rename_parent_bbscomment_parent_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuupload",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
